# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Sleepy Penguin
author: The Sleepy Penguin
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A YouTube channel for all things tech related!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Site
name: "The Sleepy Penguin"
description: "A YouTube channel for all things tech!"
meta_description: "A YouTube channel for all things tech!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
google_analytics: 
disqus: 
mailchimp-list: 

# Authors
authors:
  sleepy-penguin:
    name: The Sleepy Penguin
    display_name: The Sleepy Penguin
    author_icon: /assets/images/tux.png
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: email@email.com
    web: https://www.youtube.com/c/thesleepypenguin
    twitter: https://www.youtube.com/c/thesleepypenguin
    description: "Description goes here or something like that..."
  
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
